server:
  port: 8081
spring:
  application.name: commerce-admin
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8082/realms/commerce}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: commerce-admin
            client-secret: ${KEYCLOAK_SECRET}
            scope:
              - openid
              - microprofile-jwt
              - view_products
              - edit_products

commerce-service:
  host: ${COMMERCE_SERVICE_HOST:http://localhost}
  port: ${COMMERCE_SERVICE_PORT:8080}
  registration-id: ${COMMERCE_SERVICE_REGISTRATION_ID:keycloak}
  product.uri: /api/v1/products