spring:
  application.name: commerce-admin
server:
  port: 8081
commerce-service:
  host: ${COMMERCE_SERVICE_HOST:http://localhost}
  port: ${COMMERCE_SERVICE_PORT:8080}
  username: ${COMMERCE_SERVICE_USERNAME:service}
  password: ${COMMERCE_SERVICE_PASSWORD:password}