server:
  port: 8085
spring:
  application.name: monitoring-server
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/commerce
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: monitoring-service
            client-secret: CR0BZSwKmNk7SwHtLKrGRlKgaV22RVa9

