server:
  port: 8085
spring:
  application.name: monitoring-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:1234/realms/commerce}
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:1234/realms/commerce}
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: monitoring-service
            client-secret: ${KEYCLOAK_SECRET}
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: monitoring-service
            client-secret: ${KEYCLOAK_SECRET}
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
