server:
  port: 8085
spring:
  application.name: monitoring-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/commerce
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/commerce
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: monitoring-service
            client-secret: c1ddS5OqAxzTmj5bj2pMJ6FNo5piaZkb
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: monitoring-service
            client-secret: c1ddS5OqAxzTmj5bj2pMJ6FNo5piaZkb
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
