spring:
  application.name: commerce-service
  security:
    user:
      name: ${SECURITY_USERNAME:service}
      password: ${SECURITY_PASSWORD:password}
      roles:
        - SERVICE
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  flyway:
    enabled: true
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true