server:
  port: 8082
spring:
  application.name: commerce-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  flyway:
    enabled: true
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:1234/realms/commerce}
      client:
        registration:
          keycloak:
            client-id: commerce-service-metrics-client
            client-secret: ${KEYCLOAK_SECRET}
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:1234/realms/commerce}
  boot:
    admin:
      client:
        enabled: true
        instance:
          name: commerce-service
          service-host-type: ip
        url: http://localhost:8085

commerce-service:
  product.uri: /api/v1/products
springdoc:
  swagger-ui:
    oauth:
      client-id: commerce-swagger
      use-pkce-with-authorization-code-grant: true
keycloak:
  uri: http://localhost:1234
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
