server:
  port: 8084
spring:
  application.name: feedback-service
  data:
    mongodb:
      uri: mongodb://${DB_HOST:localhost}:${DB_PORT:27017}/${DB_NAME:feedback}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8082/realms/commerce}
