server:
  port: 8084
spring:
  application.name: feedback-service
  data:
    mongodb:
      uri: mongodb://${DB_HOST:localhost}:${DB_PORT:27017}/${DB_NAME:feedback}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8082/realms/commerce}
      client:
        registration:
          keycloak:
            client-id: feedback-service-metrics-client
            client-secret: optIrbQTGUzCjJBweSemkfgyfnpRdcM6
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/commerce
  boot:
    admin:
      client:
        enabled: true
        instance:
          name: feedback-service
          service-host-type: ip
        url: http://localhost:8085
springdoc:
  swagger-ui:
    oauth:
      client-id: feedback-swagger
      use-pkce-with-authorization-code-grant: true
keycloak:
  uri: http://localhost:8082
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'